import { transform } from "next/dist/build/swc";
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      keyframes: {
        gcStart: {
          "0%": { transform: "translateY(4vh)", opacity: "0"},
          "12%": { transform: "translate(0vh, 0vh)", opacity: "1" },
          "27%": { transform: "translateX(-13.5vh)", opacity: "1" },
          "45%": { transform: "translateX(-13.5vh)", opacity: "1" },
          "65%": { transform: "translateX(-76vh)", opacity: "1" },
          "75%": { transform: "translateX(-76vh)", opacity: "1", color: "black" },
          // "75%": { transform: "translate(-76vh, -47.5vh)", opacity: "1" },
          // "90%": { transform: "translate(-76vh, -47.5vh)", opacity: "1" },
          "100%": { transform: "translate(-76vh, -47.5vh)", opacity: "0", color: "white" },
          // "60%":{ transform: "translateX(-13.5vh)", opacity: "1" },
          // "70%": { transform: "translateX(-13.5vh)", opacity: "1" },
          // "100%": { transform: "translate(-13.5vh, -100vh)", opacity: "1" },
        },
        investStart: {
          "0%": { transform: "translateX(4vh)", opacity: "0"},
          "10%": { transform: "translateX(4vh)", opacity: "0"},
          "17%": { transform: "translateX(4vh)", opacity: "0"},
          "33%": { transform: "translateX(-1vh)", opacity: "1" },
          "45%": { transform: "translateX(-1vh)", opacity: "1" },
          "65%": { transform: "translateX(-64.5vh)", opacity: "1" },
          "75%": { transform: "translateX(-64.5vh)", opacity: "1", color: "black" },
          // "75%": { transform: "translate(-64.5vh, -47.5vh)", opacity: "1" },
          // "90%": { transform: "translate(-64.5vh, -47.5vh)", opacity: "1" },
          "100%": { transform: "translate(-64.5vh, -47.5vh)", opacity: "0", color: "white" },
          // "65%": { transform: "translateX(-1vh)", opacity: "1" },
          // "100%": { transform: "translate(-1vh, -100vh)", opacity: "1" },
        },
        leftBracket: {
          "0%": { transform: "translateX(0vh) scale(1)", opacity: "0"},
          "41%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          "45%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          "65%": { transform: "translateX(-80.5vh) scale(1.25)", opacity: "1" },
          "75%": { transform: "translateX(-80.5vh) scale(1.25)", opacity: "1", color: "black" },
          // "75%": { transform: "translate(-80.5vh, -47.5vh)", opacity: "1" },
          // "90%": { transform: "translate(-80.5vh, -47.5vh)", opacity: "1" },
          "100%": { transform: "translate(-80.5vh, -47.5vh)", opacity: "0", color: "white" },
          // "60%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          // "75%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          // "100%": { transform: "translate(-16.5vh, -100vh)", opacity: "1" },
        },
        rightBracket: {
          "0%": { transform: "translateX(0vh) scale(1)", opacity: "0"},
          "41%": { transform: "translateX(45.5vh) scale(1.25)", opacity: "1" },
          "45%": { transform: "translateX(45.5vh) scale(1.25)", opacity: "1" },
          "65%": { transform: "translateX(-15.5vh) scale(1.25)", opacity: "1" },
          "75%": { transform: "translateX(-15.5vh) scale(1.25)", opacity: "1", color: "black" },
          // "75%": { transform: "translate(-15.5vh, -47.5vh)", opacity: "1" },
          // "90%": { transform: "translate(-15.5vh, -47.5vh)", opacity: "1" },
          "100%": { transform: "translate(-15.5vh, -47.5vh)", opacity: "0", color: "white" },
          // "60%": { transform: "translateX(45.5vh) scale(1.25)", opacity: "1" },
          // "80%": { transform: "translate(45.5vh, -100vh) scale(1.25)", opacity: "1" },
          // "100%": { transform: "translate(45.5vh, -100vh) scale(1.25)", opacity: "1" },
        },
        comeIn: {
          "0%": { opacity: "0"},
          "80%": { opacity: "0" },
          "95%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        black: {
          "0%": {backgroundColor: "#ffffff" },
          "98%": {backgroundColor: "#ffffff" },
          "99%": {backgroundColor: "#ffffff" },
          "100%": { backgroundColor: "#000000" },
        },
        gcStartMobile: {
          "0%": { transform: "translateY(0vh)", opacity: "0"},
          "12%": { transform: "translateX(-14.5vh)", opacity: "1" },
          "27%": { transform: "translateX(-14.5vh)", opacity: "1" },
          "45%": { transform: "translateX(-14.5vh)", opacity: "1" },
          "55%": { transform: "translateX(-14.5vh)", opacity: "1" },
          "75%": { transform: "translateX(-14.5vh)", opacity: "1" },
          "100%": { transform: "translate(-14.5vh, -47.5vh)", opacity: "0" },
          // "60%":{ transform: "translateX(-13.5vh)", opacity: "1" },
          // "70%": { transform: "translateX(-13.5vh)", opacity: "1" },
          // "100%": { transform: "translate(-13.5vh, -100vh)", opacity: "1" },
        },
        investStartMobile: {
          "0%": { transform: "translateX(4vh)", opacity: "0"},
          "33%": { transform: "translateX(-8.5vh)", opacity: "1" },
          "45%": { transform: "translateX(-8.5vh)", opacity: "1" },
          "55%": { transform: "translateX(-8.5vh)", opacity: "1" },
          "75%": { transform: "translateX(-8.5vh)", opacity: "1" },
          "100%": { transform: "translate(-8.5vh, -47.5vh)", opacity: "0" },
          // "65%": { transform: "translateX(-1vh)", opacity: "1" },
          // "100%": { transform: "translate(-1vh, -100vh)", opacity: "1" },
        },
        leftBracketMobile: {
          "0%": { transform: "translateX(0vh) scale(1)", opacity: "0"},
          "41%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          "45%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          "55%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          "75%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          "100%": { transform: "translate(-16.5vh, -47.5vh)", opacity: "0" },
          // "60%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          // "75%": { transform: "translateX(-16.5vh) scale(1.25)", opacity: "1" },
          // "100%": { transform: "translate(-16.5vh, -100vh)", opacity: "1" },
        },
        rightBracketMobile: {
          "0%": { transform: "translateX(0vh) scale(1)", opacity: "0"},
          "41%": { transform: "translateX(15.5vh) scale(1.25)", opacity: "1" },
          "45%": { transform: "translateX(15.5vh) scale(1.25)", opacity: "1" },
          "55%": { transform: "translateX(15.5vh) scale(1.25)", opacity: "1" },
          "75%": { transform: "translateX(15.5vh) scale(1.25)", opacity: "1" },
          "100%": { transform: "translate(15.5vh, -47.5vh)", opacity: "0" },
          // "60%": { transform: "translateX(45.5vh) scale(1.25)", opacity: "1" },
          // "80%": { transform: "translate(45.5vh, -100vh) scale(1.25)", opacity: "1" },
          // "100%": { transform: "translate(45.5vh, -100vh) scale(1.25)", opacity: "1" },
        },
        comeInMobile: {
          "0%": { opacity: "0"},
          "80%": { opacity: "0" },
          "95%": { opacity: "1" },
          "100%": { opacity: "1" },
        },
        greyscaleIn: {
          "0%": { filter: "greyscale(0) invert(0) brightness(1)"},
          "100%": { filter: "greyscale(1) invert(1) brightness(0)"},
        },
        fadeRight: {
          "0%": { transform: "translateX(-4vh)", opacity: "0"},
          "100%": { transform: "translateX(0vh)", opacity: "1"},
        },
        width: {
          "0%": { width: "0%"},
          "100%": { width: "55%"},
        },
        widthMobile: {
          "0%": { width: "0%", opacity: "0"},
          "30%": { width: "0%", opacity: "0"},
          "35%": { width: "10%", opacity: "1"},
          "100%": { width: "100%", opacity: "1"},
        },
        fadeRightNav: {
          "0%": { transform: "translateX(0vh)"},
          "100%": { transform: "translateX(40vh)"},
        },
        fadeRightMob: {
          "0%": { transform: "translateX(-40vh)", opacity: "0"},
          "100%": { transform: "translateX(0vh)", opacity: "1"},
        },
        fadeRightOutMob: {
          "0%": { transform: "translateX(0vh)", opacity: "1"},
          "100%": { transform: "translateX(40vh)", opacity: "0"},
        },
        fadeLeftNav: {
          "0%": { transform: "translateX(40vh)"},
          "100%": { transform: "translateX(0vh)"},
        },
        fadeLeftMob: {
          "0%": { transform: "translateX(40vh)", opacity: "0"},
          "100%": { transform: "translateX(0vh)", opacity: "1"},
        },
        fadeLeft: {
          "0%": { transform: "translateX(4vh)", opacity: "0"},
          "100%": { transform: "translateX(0vh)", opacity: "1"},
        },
        fadeUp: {
          "0%": { transform: "translateY(8vh)", opacity: "0"},
          "100%": { transform: "translateY(0vh)", opacity: "1"},
        },
        fadeUpSlower: {
          "0%": { transform: "translateY(-4vh)", opacity: "0"},
          "100%": { transform: "translateY(0vh)", opacity: "1"},
        },
        fadeDownRightMob: {
          "0%": { transform: "translateY(0vh) rotate(0deg) scale(1)", opacity: "1"},
          "100%": { transform: "translateY(-4vh) rotate(16deg) scale(0.8)", opacity: "0"},
        },
        fadeDownLeftMob: {
          "0%": { transform: "translateY(0vh) rotate(0deg) scale(1)", opacity: "1"},
          "100%": { transform: "translateY(-4vh) rotate(-16deg) scale(0.8)", opacity: "0"},
        },
        fadeDown: {
          "0%": { transform: "translateY(-4vh)", opacity: "0"},
          "100%": { transform: "translateY(0vh)", opacity: "1"},
        },
        fadeIn: {
          "0%": { opacity: "0"},
          "100%": { opacity: "1"},
        },
        fadeOutMob: {
          "0%": { opacity: "1"},
          "90%": { opacity: "0"},
          "100%": { opacity: "0"},
        },
        fadeOut: {
          "0%": { opacity: "1",  display: "block", position: 'fixed', zIndex: '1'},
          "90%": { opacity: "0", display: "block", position: 'fixed', zIndex: '1'},
          "100%": { opacity: "0", display: "hidden", position: 'absolute', zIndex: '-1'},
        },
        fadeInMobile: {
          "0%": { opacity: "0"},
          "100%": { opacity: "1"},
        },
        spinOff: {
          "0%": { opacity: ".50", transform: "rotate(720deg)"},
          "20%": { opacity: "1", transform: ""},
          "60%": { opacity: ".50", transform: ""},
          "100%": { opacity: "1", transform: "rotate(360deg)"},
        },
      },
      animation: {
        greyscaleIn: "greyscaleIn 1s forwards cubic-bezier(.8,0,.4,1.27)",
        width: "width 2.4s forwards cubic-bezier(.17,.67,.41,.91)",
        widthMobile: "widthMobile 2.4s forwards cubic-bezier(.17,.67,.41,.91)",
        gcStart: "gcStart 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        investStart: "investStart 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        leftBracket: "leftBracket 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        rightBracket: "rightBracket 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        comeIn: "comeIn 2.9s forwards cubic-bezier(.17,.67,.4,1.18)",
        black: "black 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        gcStartMobile: "gcStartMobile 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        investStartMobile: "investStartMobile 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        leftBracketMobile: "leftBracketMobile 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        rightBracketMobile: "rightBracketMobile 3s forwards cubic-bezier(.17,.67,.4,1.18)",
        comeInMobile: "comeInMobile 2.9s forwards cubic-bezier(.17,.67,.4,1.18)",
        fadeRightMob: "fadeRightMob 1s forwards cubic-bezier(.35,.17,.2,.69)",
        fadeRightOutMob: "fadeRightOutMob 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeRightNav: "fadeRightNav 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeLeftNav: "fadeLeftNav 0.5s forwards cubic-bezier(.35,.17,.2,.69)",
        fadeLeftMob: "fadeLeftMob 0.5s forwards cubic-bezier(.35,.17,.2,.69)",
        fadeRight: "fadeRight 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeLeft: "fadeLeft 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeUp: "fadeUp 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeUpSlower: "fadeUpSlower .45s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeDown: "fadeDown 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeIn: "fadeIn 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeOut: "fadeOut 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeDownRightMob: "fadeDownRightMob 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeDownLeftMob: "fadeDownLeftMob 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeOutMob: "fadeOutMob 1s forwards cubic-bezier(.8,0,.4,1.27)",
        fadeInMobile: "fadeInMobile 0.5s forwards cubic-bezier(.8,0,.4,1.27)",
        spinOff: "spinOff 0.5s forwards cubic-bezier(.8,0,.4,1.27)",
      },
    },
  },
  plugins: [],
};
export default config;
